apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-wx-app
spec:
  selector:
    matchLabels:
      app: my-wx-app
  replicas: 4
  template:
    metadata:
      labels:
        app: my-wx-app
    spec:
      containers:
      - name: my-wx-app
        image: arvindgorur/my-wx-app:latest
        ports:
          - containerPort: 3000
        env:
          - name: OPEN_WX_API_KEY
            valueFrom:
              configMapKeyRef:
                name: apikeys
                key: openwxmap
          - name: AV_WX_API_KEY
            valueFrom:
              configMapKeyRef:
                name: apikeys
                key: checkwx
---
apiVersion: v1
kind: Service
metadata:
  name: my-wx-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: NodePort
  selector:
    app: my-wx-app
